<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use mana\Math;


class MyMathTest extends TestCase
{
//    /** @var myMathApp */
//    public $myMathApp;
//
//    public function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub+
//
//        $this->myMathApp = new Math();
//    }

    /**
     * @return void
     * @covers Math::fibonacci
     */
    public function testFibonacci() :void
    {
        // arrange
        $this->myMathApp = new Math();
        // expect
        $expect = 139583862445;
        // act
        $act = $this->myMathApp->fibonacci(55);
        // assert
        $this->assertEquals($expect,$act);

        //$this->assertEquals(139583862445, $this->myMathApp->fibonacci(55));
    }

    /**
     * @return void
     * @covers Math::factorial
     */
    public function testFactorial() :void
    {
        //arrange
        $this->myMathApp = new Math();
        // expect
        $expect = 120;
        // act
        $act = $this->myMathApp->factorial(5);
        // assert
        $this->assertEquals($expect,$act);

        //$this->assertEquals(120, $this->myMathApp->factorial(5));
    }

}